spring:
  profiles:
    active: nonprod
---
spring:
  profiles: nonprod
  data.mongodb:
    host: localhost
    port: 27017
    database: local
---
spring:
  profiles: dev
  data.mongodb:
    host: localhost
    port: 63897
    database: local
---
spring:
  profiles: test
  data.mongodb:
    host: localhost
    port: 63897
    database: local
---